## 누적합
- 주어진 데이터 셋에서 'f2' 컬럼이 1인 조건에 해당하는 데이터의 'f1'컬럼 누적합을 계산한다. 이때 발생하는 누적합 결측치는 바로 뒤의 값을 채우고, 누적합의 평균값을 출력한다. (단, 결측치 바로 뒤의 값이 없으면 다음에 나오는 값을 채워넣는다)¶

In [1]:
import pandas as pd
import numpy as np

df = pd.read_csv('/content/drive/MyDrive/빅데이터 분석기사/data/누적합/basic1.csv')

In [2]:
df

       id    age city    f1  f2   f3    f4         f5
0    id01    2.0   서울   NaN   0  NaN  ENFJ  91.297791
1    id02    9.0   서울  70.0   1  NaN  ENFJ  60.339826
2    id03   27.0   서울  61.0   1  NaN  ISTJ  17.252986
3    id04   75.0   서울   NaN   2  NaN  INFP  52.667078
4    id05   24.0   서울  85.0   2  NaN  ISFJ  29.269869
..    ...    ...  ...   ...  ..  ...   ...        ...
95   id96   92.0   경기  53.0   1  NaN  ENTJ  52.667078
96   id97  100.0   경기   NaN   0  NaN  INFP  67.886373
97   id98   39.0   경기  58.0   2  NaN  INFP  98.429899
98   id99    1.0   경기  47.0   0  NaN  ESFJ  97.381034
99  id100   47.0   경기  53.0   0  vip  ESFP  33.308999

[100 rows x 8 columns]

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 8 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   id      100 non-null    object
 1   age     100 non-null    float64
 2   city    100 non-null    object
 3   f1      69 non-null     float64
 4   f2      100 non-null    int64
 5   f3      5 non-null      object
 6   f4      100 non-null    object
 7   f5      100 non-null    float64
dtypes: float64(3), int64(1), object(4)
memory usage: 6.4+ KB

In [4]:
# 누적합 = cumsum()
df.loc[df['f2'] == 1 , 'f1'].cumsum()

1       70.0
2      131.0
6      191.0
7      292.0
9      366.0
13     416.0
14     483.0
16       NaN
19     534.0
20       NaN
21     606.0
22     681.0
25     738.0
27     772.0
33       NaN
35     849.0
37       NaN
46     924.0
49    1002.0
51    1084.0
53       NaN
55       NaN
58       NaN
62    1170.0
65       NaN
66    1222.0
69    1318.0
72       NaN
77    1414.0
80    1464.0
82    1514.0
86       NaN
88    1580.0
91    1658.0
93       NaN
94    1701.0
95    1754.0
Name: f1, dtype: float64

In [6]:
df.fillna(method = 'bfill',inplace = True)

In [7]:
df

       id    age city    f1  f2   f3    f4         f5
0    id01    2.0   서울  70.0   0  vip  ENFJ  91.297791
1    id02    9.0   서울  70.0   1  vip  ENFJ  60.339826
2    id03   27.0   서울  61.0   1  vip  ISTJ  17.252986
3    id04   75.0   서울  85.0   2  vip  INFP  52.667078
4    id05   24.0   서울  85.0   2  vip  ISFJ  29.269869
..    ...    ...  ...   ...  ..  ...   ...        ...
95   id96   92.0   경기  53.0   1  vip  ENTJ  52.667078
96   id97  100.0   경기  58.0   0  vip  INFP  67.886373
97   id98   39.0   경기  58.0   2  vip  INFP  98.429899
98   id99    1.0   경기  47.0   0  vip  ESFJ  97.381034
99  id100   47.0   경기  53.0   0  vip  ESFP  33.308999

[100 rows x 8 columns]

In [8]:
df.mean()

<ipython-input-8-c61f0c8f89b5>:1: FutureWarning: The default value of numeric_only in DataFrame.mean is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  df.mean()

age    50.963000
f1     67.300000
f2      0.650000
f5     56.734537
dtype: float64