In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
import pandas as pd

df = pd.read_csv('/content/drive/MyDrive/빅데이터 분석기사/data/mtcars.csv')

In [3]:
df.head()

,model,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
0,Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4
1,Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4
2,Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1
3,Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1
4,Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2

## 문제 1
- 자동차 데이터 셋에서 qsec 컬럼을 Min-Max Scale로 변환 후 0.5보다 큰 값을 가지는 레코드(row) 수를 묻는 문제입니다.

In [8]:
from sklearn.preprocessing import minmax_scale
df['qsec'] = minmax_scale(df['qsec'])
#df['qsec']

print(sum(df['qsec'] > 0.5))

9

In [9]:
Max_ = df['qsec'].max()
Min_ = df['qsec'].min()

mm_qsec = (df['qsec'] - Min_) / (Max_ - Min_)

In [10]:
mm_qsec

0     0.233333
1     0.300000
2     0.489286
3     0.588095
4     0.300000
5     0.680952
6     0.159524
7     0.654762
8     1.000000
9     0.452381
10    0.523810
11    0.345238
12    0.369048
13    0.416667
14    0.414286
15    0.395238
16    0.347619
17    0.591667
18    0.478571
19    0.642857
20    0.655952
21    0.282143
22    0.333333
23    0.108333
24    0.303571
25    0.523810
26    0.261905
27    0.285714
28    0.000000
29    0.119048
30    0.011905
31    0.488095
Name: qsec, dtype: float64

In [11]:
print(sum(df['qsec']>0.5))

9