## T1-27. 바닐라라떼 5점, 카페라떼 3점, 아메리카노 2점, 나머지 0점이다 총 메뉴의 점수를 더한 값은?

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [28]:
import pandas as pd
import numpy as np

df = pd.read_csv('/content/drive/MyDrive/빅데이터 분석기사/data/payment/payment.csv')

In [29]:
df

        date  hour    menu  price
0   20221129    13    딸기라떼   4000
1   20221130    12    카페라떼   3000
2   20221201    14   바닐라라떼   3500
3   20221201    16    초코라떼   3500
4   20221202    17    모카라떼   3500
5   20221202    12   카라멜라떼   3500
6   20221203     8   챠이 라떼   3500
7   20221203     9   아메리카노   2000
8   20221203    15   오곡 라떼   4000
9   20221203    16   아메리카노   2000
10  20221225    10   아메리카노   2000
11  20221225    14  토피넛 라떼   4000
12  20221225    16   카페 라떼   3000

In [33]:
df['menu'] = df['menu'].str.replace(' ','')

In [34]:
ba = sum(df['menu'].str.contains('바닐라라떼'))
ca = sum(df['menu'].str.contains('카페라떼'))
am = sum(df['menu'].str.contains('아메리카노'))

In [35]:
print((ba*5)+(ca*3)+(am*2))

17