## 결측치 처리
- 주어진 데이터에서 결측치가 80%이상 되는 컬럼은(변수는) 삭제하고, 80% 미만인 결측치가 있는 컬럼은 'city'별 중앙값으로 값을 대체하고 'f1'컬럼의 평균값을 출력하세요!

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [22]:
import pandas as pd
df = pd.read_csv('/content/drive/MyDrive/빅데이터 분석기사/data/Nulldata/basic1.csv')

In [23]:
df

       id    age city    f1  f2   f3    f4         f5
0    id01    2.0   서울   NaN   0  NaN  ENFJ  91.297791
1    id02    9.0   서울  70.0   1  NaN  ENFJ  60.339826
2    id03   27.0   서울  61.0   1  NaN  ISTJ  17.252986
3    id04   75.0   서울   NaN   2  NaN  INFP  52.667078
4    id05   24.0   서울  85.0   2  NaN  ISFJ  29.269869
..    ...    ...  ...   ...  ..  ...   ...        ...
95   id96   92.0   경기  53.0   1  NaN  ENTJ  52.667078
96   id97  100.0   경기   NaN   0  NaN  INFP  67.886373
97   id98   39.0   경기  58.0   2  NaN  INFP  98.429899
98   id99    1.0   경기  47.0   0  NaN  ESFJ  97.381034
99  id100   47.0   경기  53.0   0  vip  ESFP  33.308999

[100 rows x 8 columns]

In [24]:
na_count = df.isnull().sum()

In [25]:
all_nums = df.shape[0]
all_nums

100

In [26]:
cols = df.columns

In [27]:
drop_columns = []
for col in cols:
    print(f'컬럼 이름 : {col}/{na_count[col]}')
    print(f'결측치 비율 : {(na_count[col] / all_nums)}')
    drop_rate = (na_count[col] / all_nums)
    if drop_rate >= 0.8:
        drop_columns.append(col)

컬럼 이름 : id/0
결측치 비율 : 0.0
컬럼 이름 : age/0
결측치 비율 : 0.0
컬럼 이름 : city/0
결측치 비율 : 0.0
컬럼 이름 : f1/31
결측치 비율 : 0.31
컬럼 이름 : f2/0
결측치 비율 : 0.0
컬럼 이름 : f3/95
결측치 비율 : 0.95
컬럼 이름 : f4/0
결측치 비율 : 0.0
컬럼 이름 : f5/0
결측치 비율 : 0.0

In [28]:
drop_columns

['f3']

In [29]:
df = df.drop(drop_columns,axis = 1)

In [30]:
df

       id    age city    f1  f2    f4         f5
0    id01    2.0   서울   NaN   0  ENFJ  91.297791
1    id02    9.0   서울  70.0   1  ENFJ  60.339826
2    id03   27.0   서울  61.0   1  ISTJ  17.252986
3    id04   75.0   서울   NaN   2  INFP  52.667078
4    id05   24.0   서울  85.0   2  ISFJ  29.269869
..    ...    ...  ...   ...  ..   ...        ...
95   id96   92.0   경기  53.0   1  ENTJ  52.667078
96   id97  100.0   경기   NaN   0  INFP  67.886373
97   id98   39.0   경기  58.0   2  INFP  98.429899
98   id99    1.0   경기  47.0   0  ESFJ  97.381034
99  id100   47.0   경기  53.0   0  ESFP  33.308999

[100 rows x 7 columns]

In [36]:
f1_city = df.groupby('city')['f1'].median()
f1_city

city
경기    58.0
대구    75.0
부산    62.0
서울    68.0
Name: f1, dtype: float64

In [39]:
df.loc[(df['city'] == '서울') & (df['f1'].isnull()) , 'f1'] = f1_city['서울']
df.loc[(df['city'] == '경기') & (df['f1'].isnull()) , 'f1'] = f1_city['경기']
df.loc[(df['city'] == '대구') & (df['f1'].isnull()) , 'f1'] = f1_city['대구']
df.loc[(df['city'] == '부산') & (df['f1'].isnull()) , 'f1'] = f1_city['부산']

In [40]:
print(df['f1'].mean())

65.52